### ISSUE TITLE
Wrong char type in the Rust template

### ISSUE THREAD

**Issue by voidc** [ls1-sys-prog-course/task3-processes#1]
I think the definition of the `command` struct in Rust should use `libc::c_char` instead of Rust's `char` type.
The Rust `char` type is 4 bytes wide while in C a char is only 1 byte wide.

**Comment by Mic92** [comment]
Yes. This is correct but changing this now for everybody would be too intrusive. I will fix this for the next year.
You can fix this locally in your own project code if you want to.
